# Generated by Django 2.2.10 on 2020-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200213_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='gfg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='testtt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ghhg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
